volumes:
  mariadb_ahouais: #d√©claration du volume pour la base
 
services:
 
  # container de bdd
  database: #nom de service
    container_name: mariadb_ahouais
    image: mariadb:latest
    ports:
      - '3307:3306'
    volumes:
      - mariadb_ahouais:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Paris
      MYSQL_ROOT_PASSWORD: BatmanEgy
      MYSQL_DATABASE: ahouais
      MYSQL_USER: ahouais
      MYSQL_PASSWORD: BatmanEgy
 
  # container php
  php:
    container_name: php_ahouais
    build:
      context: ./php
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
 
  # server web
  nginx:
    container_name: nginx_ahouais
    image: nginx:stable-alpine
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: Europe/Paris
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - php
      - database 